#!/usr/bin/env bash
# This Bash script pings a specified IP address and sends 5 ICMP echo requests to check its reachability.
if [ $# -ne 1 ]
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping -c 5 "$1"
fi
