#!/usr/bin/env bash
# This script displays the content of the current directory in list format

for file in *
do
	if [[ ! $file =~ ^\. ]]
	then
		if [[ $file =~ - ]]
		then
			name=$(echo "$file" | cut -d '-' -f 2-)
			echo "$name"
		else
			echo "$file"
		fi

	fi
done
