#!/usr/bin/env bash
# This script updates the /etc/hosts file to map localhost to 127.0.0.2 and adds an entry to resolve facebook.com to 8.8.8.8.
awk -v ip="127.0.0.2" '$1 == "127.0.0.1" {$1=ip} 1' /etc/hosts | sudo tee /etc/hosts > /dev/null
echo "8.8.8.8 facebook.com" >> /etc/hosts
