#!/usr/bin/env bash
# This script extracts and displays all active IPv4 addresses configured on the local machine using ifconfig.
ifconfig | grep -oE "inet \b([0-9]{1,3}\.){3}[0-9]{1,3}\b" | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b"
